#!/bin/bash

# Update package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
/etc/init.d/nginx restart
