#!/usr/bin/env bash
# Check the number of arguments

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

PIDFILE="/var/run/my_process.pid"
start_process() {
    echo "Starting manage_my_process"
    ./manage_my_process &
    echo $! > "$PIDFILE"
    echo "manage_my_process started"
}

stop_process() {
    echo "Stopping manage_my_process"
    kill $(cat "$PIDFILE") && rm -f "$PIDFILE"
    echo "manage_my_process stopped"
}
restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
