#!/usr/bin/env bash

# Loop through numbers from 1 to 100
for ((i=1; i<=100; i++))
do
    # Check conditions for FizzBuzz, Fizz, Buzz, or the number itself
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done
