#!/usr/bin/env bash
# a Bash script that displays Best School 10 times

counter=1
while [ $counter -lt 11 ]
do

    if [ $counter -eq 4 ]; then
        echo "bad luck"

    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else 
        echo "Best School"

    fi
    ((counter++))
done
