#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 

counter=1
while [ $counter -le 20 ]
do
    # Use the case statement to check for specific iterations
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac

    # Increment the counter
    ((counter++))
done
