#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 

counter=1

# Use a while loop to loop from 1 to 20
while [ $counter -le 20 ]
do
    # Check conditions for each iteration
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    # Increment the counter
    ((counter++))
done
