#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 

counter=1

while [ $counter -lt 21 ]
do
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
