#!/usr/bin/env bash

# Loop through the files in the current directory
for file in *
do
    # Check if the file is not hidden and is a regular file
    if [ ! -h "$file" ] && [ -f "$file" ]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
