#!/bin/bash
# Create the RSA key pair with the specified number of bits and passphrase
ssh-keygen -t rsa -b 4096 -N "betty" -f school -m PEM

# Display success message
echo "RSA key pair created successfully."
